/*
WhatsApp API MultiDevice

Testing NewsletterAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package SdkWhatsappWebMultiDevice

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/aldinokemal/sdk-go-whatsapp-web-multidevice"
)

func Test_SdkWhatsappWebMultiDevice_NewsletterAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NewsletterAPIService UnfollowNewsletter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.NewsletterAPI.UnfollowNewsletter(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
