/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the UserGroupInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserGroupInfoResponse{}

// UserGroupInfoResponse struct for UserGroupInfoResponse
type UserGroupInfoResponse struct {
	Status *int32 `json:"status,omitempty"`
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// Group information object (structure may vary)
	Results map[string]interface{} `json:"results,omitempty"`
}

// NewUserGroupInfoResponse instantiates a new UserGroupInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGroupInfoResponse() *UserGroupInfoResponse {
	this := UserGroupInfoResponse{}
	return &this
}

// NewUserGroupInfoResponseWithDefaults instantiates a new UserGroupInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGroupInfoResponseWithDefaults() *UserGroupInfoResponse {
	this := UserGroupInfoResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UserGroupInfoResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupInfoResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UserGroupInfoResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *UserGroupInfoResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *UserGroupInfoResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupInfoResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *UserGroupInfoResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *UserGroupInfoResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UserGroupInfoResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupInfoResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UserGroupInfoResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UserGroupInfoResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *UserGroupInfoResponse) GetResults() map[string]interface{} {
	if o == nil || IsNil(o.Results) {
		var ret map[string]interface{}
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupInfoResponse) GetResultsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Results) {
		return map[string]interface{}{}, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *UserGroupInfoResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]interface{} and assigns it to the Results field.
func (o *UserGroupInfoResponse) SetResults(v map[string]interface{}) {
	o.Results = v
}

func (o UserGroupInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserGroupInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableUserGroupInfoResponse struct {
	value *UserGroupInfoResponse
	isSet bool
}

func (v NullableUserGroupInfoResponse) Get() *UserGroupInfoResponse {
	return v.value
}

func (v *NullableUserGroupInfoResponse) Set(val *UserGroupInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGroupInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGroupInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGroupInfoResponse(val *UserGroupInfoResponse) *NullableUserGroupInfoResponse {
	return &NullableUserGroupInfoResponse{value: val, isSet: true}
}

func (v NullableUserGroupInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGroupInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


