/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the DeviceStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceStatusResponse{}

// DeviceStatusResponse struct for DeviceStatusResponse
type DeviceStatusResponse struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *int32 `json:"status,omitempty"`
	Results *DeviceStatusResponseResults `json:"results,omitempty"`
}

// NewDeviceStatusResponse instantiates a new DeviceStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceStatusResponse() *DeviceStatusResponse {
	this := DeviceStatusResponse{}
	return &this
}

// NewDeviceStatusResponseWithDefaults instantiates a new DeviceStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceStatusResponseWithDefaults() *DeviceStatusResponse {
	this := DeviceStatusResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DeviceStatusResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStatusResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DeviceStatusResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *DeviceStatusResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeviceStatusResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStatusResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeviceStatusResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeviceStatusResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceStatusResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStatusResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *DeviceStatusResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *DeviceStatusResponse) GetResults() DeviceStatusResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret DeviceStatusResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceStatusResponse) GetResultsOk() (*DeviceStatusResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *DeviceStatusResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given DeviceStatusResponseResults and assigns it to the Results field.
func (o *DeviceStatusResponse) SetResults(v DeviceStatusResponseResults) {
	o.Results = &v
}

func (o DeviceStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableDeviceStatusResponse struct {
	value *DeviceStatusResponse
	isSet bool
}

func (v NullableDeviceStatusResponse) Get() *DeviceStatusResponse {
	return v.value
}

func (v *NullableDeviceStatusResponse) Set(val *DeviceStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceStatusResponse(val *DeviceStatusResponse) *NullableDeviceStatusResponse {
	return &NullableDeviceStatusResponse{value: val, isSet: true}
}

func (v NullableDeviceStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


