/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the ChatwootSyncHistoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatwootSyncHistoryRequest{}

// ChatwootSyncHistoryRequest struct for ChatwootSyncHistoryRequest
type ChatwootSyncHistoryRequest struct {
	// Device ID to sync (uses CHATWOOT_DEVICE_ID if not specified)
	DeviceId *string `json:"device_id,omitempty"`
	// Number of days of history to sync
	DaysLimit *int32 `json:"days_limit,omitempty"`
	// Include media attachments in sync
	IncludeMedia *bool `json:"include_media,omitempty"`
	// Include group chats in sync
	IncludeGroups *bool `json:"include_groups,omitempty"`
}

// NewChatwootSyncHistoryRequest instantiates a new ChatwootSyncHistoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatwootSyncHistoryRequest() *ChatwootSyncHistoryRequest {
	this := ChatwootSyncHistoryRequest{}
	var daysLimit int32 = 3
	this.DaysLimit = &daysLimit
	var includeMedia bool = true
	this.IncludeMedia = &includeMedia
	var includeGroups bool = true
	this.IncludeGroups = &includeGroups
	return &this
}

// NewChatwootSyncHistoryRequestWithDefaults instantiates a new ChatwootSyncHistoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatwootSyncHistoryRequestWithDefaults() *ChatwootSyncHistoryRequest {
	this := ChatwootSyncHistoryRequest{}
	var daysLimit int32 = 3
	this.DaysLimit = &daysLimit
	var includeMedia bool = true
	this.IncludeMedia = &includeMedia
	var includeGroups bool = true
	this.IncludeGroups = &includeGroups
	return &this
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *ChatwootSyncHistoryRequest) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatwootSyncHistoryRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *ChatwootSyncHistoryRequest) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *ChatwootSyncHistoryRequest) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetDaysLimit returns the DaysLimit field value if set, zero value otherwise.
func (o *ChatwootSyncHistoryRequest) GetDaysLimit() int32 {
	if o == nil || IsNil(o.DaysLimit) {
		var ret int32
		return ret
	}
	return *o.DaysLimit
}

// GetDaysLimitOk returns a tuple with the DaysLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatwootSyncHistoryRequest) GetDaysLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.DaysLimit) {
		return nil, false
	}
	return o.DaysLimit, true
}

// HasDaysLimit returns a boolean if a field has been set.
func (o *ChatwootSyncHistoryRequest) HasDaysLimit() bool {
	if o != nil && !IsNil(o.DaysLimit) {
		return true
	}

	return false
}

// SetDaysLimit gets a reference to the given int32 and assigns it to the DaysLimit field.
func (o *ChatwootSyncHistoryRequest) SetDaysLimit(v int32) {
	o.DaysLimit = &v
}

// GetIncludeMedia returns the IncludeMedia field value if set, zero value otherwise.
func (o *ChatwootSyncHistoryRequest) GetIncludeMedia() bool {
	if o == nil || IsNil(o.IncludeMedia) {
		var ret bool
		return ret
	}
	return *o.IncludeMedia
}

// GetIncludeMediaOk returns a tuple with the IncludeMedia field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatwootSyncHistoryRequest) GetIncludeMediaOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeMedia) {
		return nil, false
	}
	return o.IncludeMedia, true
}

// HasIncludeMedia returns a boolean if a field has been set.
func (o *ChatwootSyncHistoryRequest) HasIncludeMedia() bool {
	if o != nil && !IsNil(o.IncludeMedia) {
		return true
	}

	return false
}

// SetIncludeMedia gets a reference to the given bool and assigns it to the IncludeMedia field.
func (o *ChatwootSyncHistoryRequest) SetIncludeMedia(v bool) {
	o.IncludeMedia = &v
}

// GetIncludeGroups returns the IncludeGroups field value if set, zero value otherwise.
func (o *ChatwootSyncHistoryRequest) GetIncludeGroups() bool {
	if o == nil || IsNil(o.IncludeGroups) {
		var ret bool
		return ret
	}
	return *o.IncludeGroups
}

// GetIncludeGroupsOk returns a tuple with the IncludeGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatwootSyncHistoryRequest) GetIncludeGroupsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeGroups) {
		return nil, false
	}
	return o.IncludeGroups, true
}

// HasIncludeGroups returns a boolean if a field has been set.
func (o *ChatwootSyncHistoryRequest) HasIncludeGroups() bool {
	if o != nil && !IsNil(o.IncludeGroups) {
		return true
	}

	return false
}

// SetIncludeGroups gets a reference to the given bool and assigns it to the IncludeGroups field.
func (o *ChatwootSyncHistoryRequest) SetIncludeGroups(v bool) {
	o.IncludeGroups = &v
}

func (o ChatwootSyncHistoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatwootSyncHistoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceId) {
		toSerialize["device_id"] = o.DeviceId
	}
	if !IsNil(o.DaysLimit) {
		toSerialize["days_limit"] = o.DaysLimit
	}
	if !IsNil(o.IncludeMedia) {
		toSerialize["include_media"] = o.IncludeMedia
	}
	if !IsNil(o.IncludeGroups) {
		toSerialize["include_groups"] = o.IncludeGroups
	}
	return toSerialize, nil
}

type NullableChatwootSyncHistoryRequest struct {
	value *ChatwootSyncHistoryRequest
	isSet bool
}

func (v NullableChatwootSyncHistoryRequest) Get() *ChatwootSyncHistoryRequest {
	return v.value
}

func (v *NullableChatwootSyncHistoryRequest) Set(val *ChatwootSyncHistoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChatwootSyncHistoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChatwootSyncHistoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatwootSyncHistoryRequest(val *ChatwootSyncHistoryRequest) *NullableChatwootSyncHistoryRequest {
	return &NullableChatwootSyncHistoryRequest{value: val, isSet: true}
}

func (v NullableChatwootSyncHistoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatwootSyncHistoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


