/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetDisappearingTimerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDisappearingTimerRequest{}

// SetDisappearingTimerRequest struct for SetDisappearingTimerRequest
type SetDisappearingTimerRequest struct {
	// Timer in seconds: 0 (off), 86400 (24h), 604800 (7d), 7776000 (90d)
	TimerSeconds int32 `json:"timer_seconds"`
}

type _SetDisappearingTimerRequest SetDisappearingTimerRequest

// NewSetDisappearingTimerRequest instantiates a new SetDisappearingTimerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDisappearingTimerRequest(timerSeconds int32) *SetDisappearingTimerRequest {
	this := SetDisappearingTimerRequest{}
	this.TimerSeconds = timerSeconds
	return &this
}

// NewSetDisappearingTimerRequestWithDefaults instantiates a new SetDisappearingTimerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDisappearingTimerRequestWithDefaults() *SetDisappearingTimerRequest {
	this := SetDisappearingTimerRequest{}
	return &this
}

// GetTimerSeconds returns the TimerSeconds field value
func (o *SetDisappearingTimerRequest) GetTimerSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TimerSeconds
}

// GetTimerSecondsOk returns a tuple with the TimerSeconds field value
// and a boolean to check if the value has been set.
func (o *SetDisappearingTimerRequest) GetTimerSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimerSeconds, true
}

// SetTimerSeconds sets field value
func (o *SetDisappearingTimerRequest) SetTimerSeconds(v int32) {
	o.TimerSeconds = v
}

func (o SetDisappearingTimerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDisappearingTimerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timer_seconds"] = o.TimerSeconds
	return toSerialize, nil
}

func (o *SetDisappearingTimerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timer_seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDisappearingTimerRequest := _SetDisappearingTimerRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDisappearingTimerRequest)

	if err != nil {
		return err
	}

	*o = SetDisappearingTimerRequest(varSetDisappearingTimerRequest)

	return err
}

type NullableSetDisappearingTimerRequest struct {
	value *SetDisappearingTimerRequest
	isSet bool
}

func (v NullableSetDisappearingTimerRequest) Get() *SetDisappearingTimerRequest {
	return v.value
}

func (v *NullableSetDisappearingTimerRequest) Set(val *SetDisappearingTimerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDisappearingTimerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDisappearingTimerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDisappearingTimerRequest(val *SetDisappearingTimerRequest) *NullableSetDisappearingTimerRequest {
	return &NullableSetDisappearingTimerRequest{value: val, isSet: true}
}

func (v NullableSetDisappearingTimerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDisappearingTimerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


