/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the GroupInfoFromLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupInfoFromLinkResponse{}

// GroupInfoFromLinkResponse struct for GroupInfoFromLinkResponse
type GroupInfoFromLinkResponse struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *GroupInfoFromLinkResponseResults `json:"results,omitempty"`
}

// NewGroupInfoFromLinkResponse instantiates a new GroupInfoFromLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupInfoFromLinkResponse() *GroupInfoFromLinkResponse {
	this := GroupInfoFromLinkResponse{}
	return &this
}

// NewGroupInfoFromLinkResponseWithDefaults instantiates a new GroupInfoFromLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupInfoFromLinkResponseWithDefaults() *GroupInfoFromLinkResponse {
	this := GroupInfoFromLinkResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GroupInfoFromLinkResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupInfoFromLinkResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GroupInfoFromLinkResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GroupInfoFromLinkResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GroupInfoFromLinkResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupInfoFromLinkResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GroupInfoFromLinkResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GroupInfoFromLinkResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GroupInfoFromLinkResponse) GetResults() GroupInfoFromLinkResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret GroupInfoFromLinkResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupInfoFromLinkResponse) GetResultsOk() (*GroupInfoFromLinkResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GroupInfoFromLinkResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given GroupInfoFromLinkResponseResults and assigns it to the Results field.
func (o *GroupInfoFromLinkResponse) SetResults(v GroupInfoFromLinkResponseResults) {
	o.Results = &v
}

func (o GroupInfoFromLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupInfoFromLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableGroupInfoFromLinkResponse struct {
	value *GroupInfoFromLinkResponse
	isSet bool
}

func (v NullableGroupInfoFromLinkResponse) Get() *GroupInfoFromLinkResponse {
	return v.value
}

func (v *NullableGroupInfoFromLinkResponse) Set(val *GroupInfoFromLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupInfoFromLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupInfoFromLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupInfoFromLinkResponse(val *GroupInfoFromLinkResponse) *NullableGroupInfoFromLinkResponse {
	return &NullableGroupInfoFromLinkResponse{value: val, isSet: true}
}

func (v NullableGroupInfoFromLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupInfoFromLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


