/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the GroupParticipantItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupParticipantItem{}

// GroupParticipantItem struct for GroupParticipantItem
type GroupParticipantItem struct {
	Jid *string `json:"jid,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	Lid NullableString `json:"lid,omitempty"`
	DisplayName NullableString `json:"display_name,omitempty"`
	IsAdmin *bool `json:"is_admin,omitempty"`
	IsSuperAdmin *bool `json:"is_super_admin,omitempty"`
}

// NewGroupParticipantItem instantiates a new GroupParticipantItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupParticipantItem() *GroupParticipantItem {
	this := GroupParticipantItem{}
	return &this
}

// NewGroupParticipantItemWithDefaults instantiates a new GroupParticipantItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupParticipantItemWithDefaults() *GroupParticipantItem {
	this := GroupParticipantItem{}
	return &this
}

// GetJid returns the Jid field value if set, zero value otherwise.
func (o *GroupParticipantItem) GetJid() string {
	if o == nil || IsNil(o.Jid) {
		var ret string
		return ret
	}
	return *o.Jid
}

// GetJidOk returns a tuple with the Jid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupParticipantItem) GetJidOk() (*string, bool) {
	if o == nil || IsNil(o.Jid) {
		return nil, false
	}
	return o.Jid, true
}

// HasJid returns a boolean if a field has been set.
func (o *GroupParticipantItem) HasJid() bool {
	if o != nil && !IsNil(o.Jid) {
		return true
	}

	return false
}

// SetJid gets a reference to the given string and assigns it to the Jid field.
func (o *GroupParticipantItem) SetJid(v string) {
	o.Jid = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *GroupParticipantItem) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupParticipantItem) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *GroupParticipantItem) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *GroupParticipantItem) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetLid returns the Lid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupParticipantItem) GetLid() string {
	if o == nil || IsNil(o.Lid.Get()) {
		var ret string
		return ret
	}
	return *o.Lid.Get()
}

// GetLidOk returns a tuple with the Lid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupParticipantItem) GetLidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lid.Get(), o.Lid.IsSet()
}

// HasLid returns a boolean if a field has been set.
func (o *GroupParticipantItem) HasLid() bool {
	if o != nil && o.Lid.IsSet() {
		return true
	}

	return false
}

// SetLid gets a reference to the given NullableString and assigns it to the Lid field.
func (o *GroupParticipantItem) SetLid(v string) {
	o.Lid.Set(&v)
}
// SetLidNil sets the value for Lid to be an explicit nil
func (o *GroupParticipantItem) SetLidNil() {
	o.Lid.Set(nil)
}

// UnsetLid ensures that no value is present for Lid, not even an explicit nil
func (o *GroupParticipantItem) UnsetLid() {
	o.Lid.Unset()
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroupParticipantItem) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupParticipantItem) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *GroupParticipantItem) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *GroupParticipantItem) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *GroupParticipantItem) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *GroupParticipantItem) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetIsAdmin returns the IsAdmin field value if set, zero value otherwise.
func (o *GroupParticipantItem) GetIsAdmin() bool {
	if o == nil || IsNil(o.IsAdmin) {
		var ret bool
		return ret
	}
	return *o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupParticipantItem) GetIsAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAdmin) {
		return nil, false
	}
	return o.IsAdmin, true
}

// HasIsAdmin returns a boolean if a field has been set.
func (o *GroupParticipantItem) HasIsAdmin() bool {
	if o != nil && !IsNil(o.IsAdmin) {
		return true
	}

	return false
}

// SetIsAdmin gets a reference to the given bool and assigns it to the IsAdmin field.
func (o *GroupParticipantItem) SetIsAdmin(v bool) {
	o.IsAdmin = &v
}

// GetIsSuperAdmin returns the IsSuperAdmin field value if set, zero value otherwise.
func (o *GroupParticipantItem) GetIsSuperAdmin() bool {
	if o == nil || IsNil(o.IsSuperAdmin) {
		var ret bool
		return ret
	}
	return *o.IsSuperAdmin
}

// GetIsSuperAdminOk returns a tuple with the IsSuperAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupParticipantItem) GetIsSuperAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSuperAdmin) {
		return nil, false
	}
	return o.IsSuperAdmin, true
}

// HasIsSuperAdmin returns a boolean if a field has been set.
func (o *GroupParticipantItem) HasIsSuperAdmin() bool {
	if o != nil && !IsNil(o.IsSuperAdmin) {
		return true
	}

	return false
}

// SetIsSuperAdmin gets a reference to the given bool and assigns it to the IsSuperAdmin field.
func (o *GroupParticipantItem) SetIsSuperAdmin(v bool) {
	o.IsSuperAdmin = &v
}

func (o GroupParticipantItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupParticipantItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Jid) {
		toSerialize["jid"] = o.Jid
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if o.Lid.IsSet() {
		toSerialize["lid"] = o.Lid.Get()
	}
	if o.DisplayName.IsSet() {
		toSerialize["display_name"] = o.DisplayName.Get()
	}
	if !IsNil(o.IsAdmin) {
		toSerialize["is_admin"] = o.IsAdmin
	}
	if !IsNil(o.IsSuperAdmin) {
		toSerialize["is_super_admin"] = o.IsSuperAdmin
	}
	return toSerialize, nil
}

type NullableGroupParticipantItem struct {
	value *GroupParticipantItem
	isSet bool
}

func (v NullableGroupParticipantItem) Get() *GroupParticipantItem {
	return v.value
}

func (v *NullableGroupParticipantItem) Set(val *GroupParticipantItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupParticipantItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupParticipantItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupParticipantItem(val *GroupParticipantItem) *NullableGroupParticipantItem {
	return &NullableGroupParticipantItem{value: val, isSet: true}
}

func (v NullableGroupParticipantItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupParticipantItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


