/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 5.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the NewsletterState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewsletterState{}

// NewsletterState struct for NewsletterState
type NewsletterState struct {
	Type *string `json:"type,omitempty"`
}

// NewNewsletterState instantiates a new NewsletterState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsletterState() *NewsletterState {
	this := NewsletterState{}
	return &this
}

// NewNewsletterStateWithDefaults instantiates a new NewsletterState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsletterStateWithDefaults() *NewsletterState {
	this := NewsletterState{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NewsletterState) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsletterState) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NewsletterState) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NewsletterState) SetType(v string) {
	o.Type = &v
}

func (o NewsletterState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewsletterState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableNewsletterState struct {
	value *NewsletterState
	isSet bool
}

func (v NullableNewsletterState) Get() *NewsletterState {
	return v.value
}

func (v *NullableNewsletterState) Set(val *NewsletterState) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsletterState) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsletterState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsletterState(val *NewsletterState) *NullableNewsletterState {
	return &NullableNewsletterState{value: val, isSet: true}
}

func (v NullableNewsletterState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsletterState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


