/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the SetDisappearingTimerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDisappearingTimerResponse{}

// SetDisappearingTimerResponse struct for SetDisappearingTimerResponse
type SetDisappearingTimerResponse struct {
	Status *int32 `json:"status,omitempty"`
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *SetDisappearingTimerResponseResults `json:"results,omitempty"`
}

// NewSetDisappearingTimerResponse instantiates a new SetDisappearingTimerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDisappearingTimerResponse() *SetDisappearingTimerResponse {
	this := SetDisappearingTimerResponse{}
	return &this
}

// NewSetDisappearingTimerResponseWithDefaults instantiates a new SetDisappearingTimerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDisappearingTimerResponseWithDefaults() *SetDisappearingTimerResponse {
	this := SetDisappearingTimerResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SetDisappearingTimerResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetDisappearingTimerResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SetDisappearingTimerResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *SetDisappearingTimerResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SetDisappearingTimerResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetDisappearingTimerResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SetDisappearingTimerResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SetDisappearingTimerResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SetDisappearingTimerResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetDisappearingTimerResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SetDisappearingTimerResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SetDisappearingTimerResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *SetDisappearingTimerResponse) GetResults() SetDisappearingTimerResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret SetDisappearingTimerResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetDisappearingTimerResponse) GetResultsOk() (*SetDisappearingTimerResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *SetDisappearingTimerResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given SetDisappearingTimerResponseResults and assigns it to the Results field.
func (o *SetDisappearingTimerResponse) SetResults(v SetDisappearingTimerResponseResults) {
	o.Results = &v
}

func (o SetDisappearingTimerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDisappearingTimerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableSetDisappearingTimerResponse struct {
	value *SetDisappearingTimerResponse
	isSet bool
}

func (v NullableSetDisappearingTimerResponse) Get() *SetDisappearingTimerResponse {
	return v.value
}

func (v *NullableSetDisappearingTimerResponse) Set(val *SetDisappearingTimerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDisappearingTimerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDisappearingTimerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDisappearingTimerResponse(val *SetDisappearingTimerResponse) *NullableSetDisappearingTimerResponse {
	return &NullableSetDisappearingTimerResponse{value: val, isSet: true}
}

func (v NullableSetDisappearingTimerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDisappearingTimerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


