/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetGroupNameRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetGroupNameRequest{}

// SetGroupNameRequest struct for SetGroupNameRequest
type SetGroupNameRequest struct {
	// The group ID
	GroupId string `json:"group_id"`
	// The new group name (max 25 characters)
	Name string `json:"name"`
}

type _SetGroupNameRequest SetGroupNameRequest

// NewSetGroupNameRequest instantiates a new SetGroupNameRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetGroupNameRequest(groupId string, name string) *SetGroupNameRequest {
	this := SetGroupNameRequest{}
	this.GroupId = groupId
	this.Name = name
	return &this
}

// NewSetGroupNameRequestWithDefaults instantiates a new SetGroupNameRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetGroupNameRequestWithDefaults() *SetGroupNameRequest {
	this := SetGroupNameRequest{}
	return &this
}

// GetGroupId returns the GroupId field value
func (o *SetGroupNameRequest) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *SetGroupNameRequest) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *SetGroupNameRequest) SetGroupId(v string) {
	o.GroupId = v
}

// GetName returns the Name field value
func (o *SetGroupNameRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetGroupNameRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetGroupNameRequest) SetName(v string) {
	o.Name = v
}

func (o SetGroupNameRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetGroupNameRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group_id"] = o.GroupId
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SetGroupNameRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetGroupNameRequest := _SetGroupNameRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetGroupNameRequest)

	if err != nil {
		return err
	}

	*o = SetGroupNameRequest(varSetGroupNameRequest)

	return err
}

type NullableSetGroupNameRequest struct {
	value *SetGroupNameRequest
	isSet bool
}

func (v NullableSetGroupNameRequest) Get() *SetGroupNameRequest {
	return v.value
}

func (v *NullableSetGroupNameRequest) Set(val *SetGroupNameRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetGroupNameRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetGroupNameRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetGroupNameRequest(val *SetGroupNameRequest) *NullableSetGroupNameRequest {
	return &NullableSetGroupNameRequest{value: val, isSet: true}
}

func (v NullableSetGroupNameRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetGroupNameRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


