/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the PinChatResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PinChatResponse{}

// PinChatResponse struct for PinChatResponse
type PinChatResponse struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *PinChatResponseResults `json:"results,omitempty"`
}

// NewPinChatResponse instantiates a new PinChatResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPinChatResponse() *PinChatResponse {
	this := PinChatResponse{}
	return &this
}

// NewPinChatResponseWithDefaults instantiates a new PinChatResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPinChatResponseWithDefaults() *PinChatResponse {
	this := PinChatResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PinChatResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PinChatResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PinChatResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PinChatResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PinChatResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PinChatResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PinChatResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PinChatResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *PinChatResponse) GetResults() PinChatResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret PinChatResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PinChatResponse) GetResultsOk() (*PinChatResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *PinChatResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given PinChatResponseResults and assigns it to the Results field.
func (o *PinChatResponse) SetResults(v PinChatResponseResults) {
	o.Results = &v
}

func (o PinChatResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PinChatResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullablePinChatResponse struct {
	value *PinChatResponse
	isSet bool
}

func (v NullablePinChatResponse) Get() *PinChatResponse {
	return v.value
}

func (v *NullablePinChatResponse) Set(val *PinChatResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePinChatResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePinChatResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePinChatResponse(val *PinChatResponse) *NullablePinChatResponse {
	return &NullablePinChatResponse{value: val, isSet: true}
}

func (v NullablePinChatResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePinChatResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


