/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the MyListContactsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MyListContactsResponse{}

// MyListContactsResponse struct for MyListContactsResponse
type MyListContactsResponse struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *MyListContactsResponseResults `json:"results,omitempty"`
}

// NewMyListContactsResponse instantiates a new MyListContactsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMyListContactsResponse() *MyListContactsResponse {
	this := MyListContactsResponse{}
	return &this
}

// NewMyListContactsResponseWithDefaults instantiates a new MyListContactsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMyListContactsResponseWithDefaults() *MyListContactsResponse {
	this := MyListContactsResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *MyListContactsResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MyListContactsResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *MyListContactsResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *MyListContactsResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MyListContactsResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MyListContactsResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MyListContactsResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MyListContactsResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *MyListContactsResponse) GetResults() MyListContactsResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret MyListContactsResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MyListContactsResponse) GetResultsOk() (*MyListContactsResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *MyListContactsResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given MyListContactsResponseResults and assigns it to the Results field.
func (o *MyListContactsResponse) SetResults(v MyListContactsResponseResults) {
	o.Results = &v
}

func (o MyListContactsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MyListContactsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableMyListContactsResponse struct {
	value *MyListContactsResponse
	isSet bool
}

func (v NullableMyListContactsResponse) Get() *MyListContactsResponse {
	return v.value
}

func (v *NullableMyListContactsResponse) Set(val *MyListContactsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMyListContactsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMyListContactsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMyListContactsResponse(val *MyListContactsResponse) *NullableMyListContactsResponse {
	return &NullableMyListContactsResponse{value: val, isSet: true}
}

func (v NullableMyListContactsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMyListContactsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


