/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the AddDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddDeviceRequest{}

// AddDeviceRequest struct for AddDeviceRequest
type AddDeviceRequest struct {
	// Optional custom device ID. If not provided, one will be generated.
	DeviceId *string `json:"device_id,omitempty"`
}

// NewAddDeviceRequest instantiates a new AddDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddDeviceRequest() *AddDeviceRequest {
	this := AddDeviceRequest{}
	return &this
}

// NewAddDeviceRequestWithDefaults instantiates a new AddDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddDeviceRequestWithDefaults() *AddDeviceRequest {
	this := AddDeviceRequest{}
	return &this
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *AddDeviceRequest) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddDeviceRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *AddDeviceRequest) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *AddDeviceRequest) SetDeviceId(v string) {
	o.DeviceId = &v
}

func (o AddDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceId) {
		toSerialize["device_id"] = o.DeviceId
	}
	return toSerialize, nil
}

type NullableAddDeviceRequest struct {
	value *AddDeviceRequest
	isSet bool
}

func (v NullableAddDeviceRequest) Get() *AddDeviceRequest {
	return v.value
}

func (v *NullableAddDeviceRequest) Set(val *AddDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddDeviceRequest(val *AddDeviceRequest) *NullableAddDeviceRequest {
	return &NullableAddDeviceRequest{value: val, isSet: true}
}

func (v NullableAddDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


