/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the ArchiveChatResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArchiveChatResponse{}

// ArchiveChatResponse struct for ArchiveChatResponse
type ArchiveChatResponse struct {
	Status *int32 `json:"status,omitempty"`
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *ArchiveChatResponseResults `json:"results,omitempty"`
}

// NewArchiveChatResponse instantiates a new ArchiveChatResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArchiveChatResponse() *ArchiveChatResponse {
	this := ArchiveChatResponse{}
	return &this
}

// NewArchiveChatResponseWithDefaults instantiates a new ArchiveChatResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArchiveChatResponseWithDefaults() *ArchiveChatResponse {
	this := ArchiveChatResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ArchiveChatResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveChatResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ArchiveChatResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ArchiveChatResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ArchiveChatResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveChatResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ArchiveChatResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ArchiveChatResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ArchiveChatResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveChatResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ArchiveChatResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ArchiveChatResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ArchiveChatResponse) GetResults() ArchiveChatResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret ArchiveChatResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveChatResponse) GetResultsOk() (*ArchiveChatResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ArchiveChatResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given ArchiveChatResponseResults and assigns it to the Results field.
func (o *ArchiveChatResponse) SetResults(v ArchiveChatResponseResults) {
	o.Results = &v
}

func (o ArchiveChatResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArchiveChatResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableArchiveChatResponse struct {
	value *ArchiveChatResponse
	isSet bool
}

func (v NullableArchiveChatResponse) Get() *ArchiveChatResponse {
	return v.value
}

func (v *NullableArchiveChatResponse) Set(val *ArchiveChatResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableArchiveChatResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableArchiveChatResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchiveChatResponse(val *ArchiveChatResponse) *NullableArchiveChatResponse {
	return &NullableArchiveChatResponse{value: val, isSet: true}
}

func (v NullableArchiveChatResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchiveChatResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


