/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API

API version: 6.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the ChatMessagesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatMessagesResponse{}

// ChatMessagesResponse struct for ChatMessagesResponse
type ChatMessagesResponse struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *ChatMessagesResponseResults `json:"results,omitempty"`
}

// NewChatMessagesResponse instantiates a new ChatMessagesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatMessagesResponse() *ChatMessagesResponse {
	this := ChatMessagesResponse{}
	return &this
}

// NewChatMessagesResponseWithDefaults instantiates a new ChatMessagesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatMessagesResponseWithDefaults() *ChatMessagesResponse {
	this := ChatMessagesResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ChatMessagesResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatMessagesResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ChatMessagesResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ChatMessagesResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ChatMessagesResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatMessagesResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ChatMessagesResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ChatMessagesResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ChatMessagesResponse) GetResults() ChatMessagesResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret ChatMessagesResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatMessagesResponse) GetResultsOk() (*ChatMessagesResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ChatMessagesResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given ChatMessagesResponseResults and assigns it to the Results field.
func (o *ChatMessagesResponse) SetResults(v ChatMessagesResponseResults) {
	o.Results = &v
}

func (o ChatMessagesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatMessagesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableChatMessagesResponse struct {
	value *ChatMessagesResponse
	isSet bool
}

func (v NullableChatMessagesResponse) Get() *ChatMessagesResponse {
	return v.value
}

func (v *NullableChatMessagesResponse) Set(val *ChatMessagesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChatMessagesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChatMessagesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatMessagesResponse(val *ChatMessagesResponse) *NullableChatMessagesResponse {
	return &NullableChatMessagesResponse{value: val, isSet: true}
}

func (v NullableChatMessagesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatMessagesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


