/*
WhatsApp API MultiDevice

This API is used for sending whatsapp via API.  Device scoping: - Send `X-Device-Id` on all device-scoped REST calls. - WebSocket: connect to `/ws?device_id=<id>`. 

API version: 8.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SdkWhatsappWebMultiDevice

import (
	"encoding/json"
)

// checks if the DownloadMessageMedia200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadMessageMedia200Response{}

// DownloadMessageMedia200Response struct for DownloadMessageMedia200Response
type DownloadMessageMedia200Response struct {
	Status *int32 `json:"status,omitempty"`
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Results *DownloadMessageMedia200ResponseResults `json:"results,omitempty"`
}

// NewDownloadMessageMedia200Response instantiates a new DownloadMessageMedia200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadMessageMedia200Response() *DownloadMessageMedia200Response {
	this := DownloadMessageMedia200Response{}
	return &this
}

// NewDownloadMessageMedia200ResponseWithDefaults instantiates a new DownloadMessageMedia200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadMessageMedia200ResponseWithDefaults() *DownloadMessageMedia200Response {
	this := DownloadMessageMedia200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DownloadMessageMedia200Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadMessageMedia200Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DownloadMessageMedia200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *DownloadMessageMedia200Response) SetStatus(v int32) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DownloadMessageMedia200Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadMessageMedia200Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DownloadMessageMedia200Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *DownloadMessageMedia200Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DownloadMessageMedia200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadMessageMedia200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DownloadMessageMedia200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DownloadMessageMedia200Response) SetMessage(v string) {
	o.Message = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *DownloadMessageMedia200Response) GetResults() DownloadMessageMedia200ResponseResults {
	if o == nil || IsNil(o.Results) {
		var ret DownloadMessageMedia200ResponseResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadMessageMedia200Response) GetResultsOk() (*DownloadMessageMedia200ResponseResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *DownloadMessageMedia200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given DownloadMessageMedia200ResponseResults and assigns it to the Results field.
func (o *DownloadMessageMedia200Response) SetResults(v DownloadMessageMedia200ResponseResults) {
	o.Results = &v
}

func (o DownloadMessageMedia200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadMessageMedia200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableDownloadMessageMedia200Response struct {
	value *DownloadMessageMedia200Response
	isSet bool
}

func (v NullableDownloadMessageMedia200Response) Get() *DownloadMessageMedia200Response {
	return v.value
}

func (v *NullableDownloadMessageMedia200Response) Set(val *DownloadMessageMedia200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadMessageMedia200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadMessageMedia200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadMessageMedia200Response(val *DownloadMessageMedia200Response) *NullableDownloadMessageMedia200Response {
	return &NullableDownloadMessageMedia200Response{value: val, isSet: true}
}

func (v NullableDownloadMessageMedia200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadMessageMedia200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


